name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_nodejs:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
    
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Provisioning
        run: |
          docker --version
          node -v
          docker pull ubuntu
          pwd
          cd ../
          git clone --depth=50 --branch=master https://github.com/apocas/dockerode.git
          cd dockerode
          npm install
          cd ../docker-modem
          
      - name: NPM install
        run: npm install
      
      - name: NPM test
        run: npm test
            
      - name: Dockerode test suite
        run: |
          cd ../dockerode
          rm -rf ./node_modules/docker-modem
          pwd
          ls ../
          cp -R ../docker-modem ./node_modules/docker-modem
          if [ "${{ matrix.node-version }}" = "14.x" ] || [ "${{ matrix.node-version }}" = "16.x" ] || [ "${{ matrix.node-version }}" = "18.x" ] || [ "${{ matrix.node-version }}" = "19.x" ]; then
            npm test -- --grep "buildKit|BuildKit" --invert
          else
            npm test
          fi
